base_url = "https://example.com"
title = "Stockholm"
generate_rss = true
rss_limit = 10
compile_sass = true
highlight_code = false
build_search_index = false

taxonomies = [
    { name = "categories" },
    { name = "tags" }
]

[extra]
# Theme
theme_color = "#000000"

# Hero
name = "Sven Svensson"
occupation = "Bit Wrangler"
social_links = [
    { url = "https://www.facebook.com", icon = "facebook"},
    { url = "https://twitter.com/", icon = "twitter"},
    { url = "https://github.com/", icon = "github"},
    { url = "https://linkedin.com/", icon = "linkedin"},
]
introduction = "Welcome! This site is built with the static site generator Zola using the Stockholm theme. Have a look around, and hope you like it :)"
hero_bg_alt = "Description of background image"

# Nav
navigation = [
    { url = "/", name = "Home", icon = "home" },
    { url = "/about", name = "About", icon = "user" },
    { url = "/articles", name = "Articles", icon = "file-text" },
    { url = "/gallery", name = "Gallery", icon = "image" },
]

# Javascript enhancements
preload = "viewport" # https://instant.page/v3
scroll_nav = "show" # hide || show

