base_url = "https://example.com"
title = "Stockholm"
generate_rss = true
rss_limit = 10
compile_sass = true
highlight_code = false
build_search_index = false

taxonomies = [
    { name = "tags" },
    { name = "categories" }
]

[extra]
name = "Mathias Iversen"
description = "Software Developer"
social_links = [
    { url = "https://www.facebook.com", icon = "facebook"},
    { url = "https://twitter.com/", icon = "twitter"},
    { url = "https://github.com/", icon = "github"},
    { url = "https://linkedin.com/", icon = "linkedin"},
]
navigation = [
    { url = "/", name = "Home", icon = "home" },
    { url = "/about", name = "About", icon = "user" },
    { url = "/text", name = "Text", icon = "file-text" },
    { url = "/pictures", name = "Pictures", icon = "image" },
    # { url = "/settings", name = "Settings", icon = "settings" },
]
prefetch = "quicklink"

