base_url = "https://example.com"
title = "Stockholm"
generate_rss = true
rss_limit = 10
compile_sass = true
highlight_code = false
build_search_index = false

taxonomies = [
    { name = "categories" },
    { name = "tags" }
]

[extra]
name = "Mathias Iversen"
occupation = "Software Developer"
introduction = "Hello stranger! This is my small corner of the web. I'll use this website to showcase stuff that I do, write, or take pictures of. Hope you enjoy it :)"
social_links = [
    { url = "https://www.facebook.com", icon = "facebook"},
    { url = "https://twitter.com/", icon = "twitter"},
    { url = "https://github.com/", icon = "github"},
    { url = "https://linkedin.com/", icon = "linkedin"},
]
navigation = [
    { url = "/", name = "Home", icon = "home" },
    { url = "/about", name = "About", icon = "user" },
    { url = "/articles", name = "Articles", icon = "file-text" },
    { url = "/gallery", name = "Gallery", icon = "image" },
]
preload = "viewport" # https://instant.page/v3
theme_color = "#000000"
scroll_nav = "show" # hide || show

