name = "stockholm"
description = "A minimalistic theme"
license = "MIT"
homepage = ""
min_version = "0.8.0"
demo = ""

[extra]

# The theme author info: you!
[author]
name = "Mathias Iversen"
homepage = "https://www.mathiasiversen.com"